/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 13 10:48:28 GMT 2018
 */

package utils;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.landlord.dto.UserDTO;
import com.landlord.models.User;
import com.landlord.utils.UserMapperImpl;
import java.util.ConcurrentModificationException;
import java.util.LinkedList;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UserMapperImpl_ESTest extends UserMapperImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      UserMapperImpl userMapperImpl0 = new UserMapperImpl();
      LinkedList<UserDTO> linkedList0 = new LinkedList<UserDTO>();
      List<User> list0 = userMapperImpl0.mapManyToModel(linkedList0);
      List<UserDTO> list1 = userMapperImpl0.mapMany(list0);
      assertTrue(list1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      UserMapperImpl userMapperImpl0 = new UserMapperImpl();
      UserDTO userDTO0 = new UserDTO();
      LinkedList<UserDTO> linkedList0 = new LinkedList<UserDTO>();
      List<UserDTO> list0 = linkedList0.subList(0, 0);
      linkedList0.add(userDTO0);
      // Undeclared exception!
      try { 
        userMapperImpl0.mapManyToModel(list0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.util.SubList", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      UserMapperImpl userMapperImpl0 = new UserMapperImpl();
      // Undeclared exception!
      try { 
        userMapperImpl0.mapManyToModel((List<UserDTO>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.landlord.utils.UserMapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      UserMapperImpl userMapperImpl0 = new UserMapperImpl();
      // Undeclared exception!
      try { 
        userMapperImpl0.mapMany((List<User>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.landlord.utils.UserMapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      UserMapperImpl userMapperImpl0 = new UserMapperImpl();
      // Undeclared exception!
      try { 
        userMapperImpl0.map((User) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.landlord.utils.UserMapperImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      UserMapperImpl userMapperImpl0 = new UserMapperImpl();
      // Undeclared exception!
      try { 
        userMapperImpl0.map((UserDTO) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.landlord.utils.UserMapperImpl", e);
      }
  }
}
