/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 13 11:10:13 GMT 2018
 */

package com.landlord.api.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import com.landlord.dto.ChatMessageInputDTO;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChatMessageInputDTO_ESTest extends ChatMessageInputDTO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      String string0 = chatMessageInputDTO0.getMessageSenderUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      chatMessageInputDTO0.message = "G0#G(2.BHGV";
      String string0 = chatMessageInputDTO0.getMessage();
      assertEquals("G0#G(2.BHGV", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      chatMessageInputDTO0.message = "G0#G(2.BHGV";
      chatMessageInputDTO0.message = "";
      String string0 = chatMessageInputDTO0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      chatMessageInputDTO0.estateId = ":`GR.g<{";
      String string0 = chatMessageInputDTO0.getEstateId();
      assertEquals(":`GR.g<{", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      chatMessageInputDTO0.setEstateId("");
      String string0 = chatMessageInputDTO0.getEstateId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      String string0 = chatMessageInputDTO0.getEstateId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      chatMessageInputDTO0.setMessageSenderUsername("");
      String string0 = chatMessageInputDTO0.getMessageSenderUsername();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      chatMessageInputDTO0.setMessage("");
      assertEquals(0, chatMessageInputDTO0.id);
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      String string0 = chatMessageInputDTO0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO("MTXB'\"{SBPa}oXlHIk9", "cOY*)Y,HapD-.CCl5", "]^$]zR-??ETqsF");
      String string0 = chatMessageInputDTO0.getMessageSenderUsername();
      assertEquals("cOY*)Y,HapD-.CCl5", chatMessageInputDTO0.getEstateId());
      assertNotNull(string0);
      assertEquals("]^$]zR-??ETqsF", string0);
      assertEquals("MTXB'\"{SBPa}oXlHIk9", chatMessageInputDTO0.getMessage());
  }
}
