/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 13 12:12:10 GMT 2018
 */

package com.landlord.api.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import com.landlord.dto.ChatMessageInputDTO;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ChatMessageInputDTO_ESTest extends ChatMessageInputDTO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      chatMessageInputDTO0.setEstateId("\"JXYG");
      String string0 = chatMessageInputDTO0.getMessageSenderUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      chatMessageInputDTO0.message = "\"JXYG";
      String string0 = chatMessageInputDTO0.getMessageSenderUsername();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      chatMessageInputDTO0.setEstateId("\"JXYG");
      String string0 = chatMessageInputDTO0.getEstateId();
      assertEquals("\"JXYG", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      chatMessageInputDTO0.message = "\"JXYG";
      String string0 = chatMessageInputDTO0.getMessage();
      assertEquals("\"JXYG", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO("com.landlord.dto.ChatMessageInputDTO", "com.landlord.dto.ChatMessageInputDTO", "com.landlord.dto.ChatMessageInputDTO");
      chatMessageInputDTO0.messageSenderUsername = "com.landlord.dto.ChatMessageInputDTO";
      String string0 = chatMessageInputDTO0.getMessage();
      assertEquals("com.landlord.dto.ChatMessageInputDTO", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO("com.landlord.dto.ChatMessageInputDTO", "com.landlord.dto.ChatMessageInputDTO", "com.landlord.dto.ChatMessageInputDTO");
      String string0 = chatMessageInputDTO0.getMessageSenderUsername();
      assertEquals("com.landlord.dto.ChatMessageInputDTO", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      String string0 = chatMessageInputDTO0.getMessage();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO("", "", "");
      String string0 = chatMessageInputDTO0.getEstateId();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO();
      String string0 = chatMessageInputDTO0.getEstateId();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO("", "", "");
      chatMessageInputDTO0.setMessageSenderUsername("com.landlord.dto.base.DTOModelBase");
      assertEquals("com.landlord.dto.base.DTOModelBase", chatMessageInputDTO0.getMessageSenderUsername());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO("", "", "");
      chatMessageInputDTO0.setMessage("");
      assertEquals("", chatMessageInputDTO0.getMessage());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO("", "", "");
      String string0 = chatMessageInputDTO0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ChatMessageInputDTO chatMessageInputDTO0 = new ChatMessageInputDTO("", "", "");
      String string0 = chatMessageInputDTO0.getMessageSenderUsername();
      assertEquals("", string0);
  }
}
