/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 13 12:09:15 GMT 2018
 */

package com.landlord.api.dto;

import org.junit.Test;
import static org.junit.Assert.*;
import com.landlord.dto.UserDTO;
import com.landlord.models.base.UserType;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UserDTO_ESTest extends UserDTO_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      userDTO0.setUserName("$\"Sdb02cO1eY%^&`");
      String string0 = userDTO0.getFirstName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      UserType userType0 = UserType.TENANT;
      userDTO0.setUserType(userType0);
      UserType userType1 = userDTO0.getUserType();
      assertSame(userType1, userType0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      userDTO0.setUserName("$\"Sdb02cO1eY%^&`");
      String string0 = userDTO0.getUserName();
      assertEquals("$\"Sdb02cO1eY%^&`", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      UserType userType0 = UserType.LANDLORD;
      UserDTO userDTO0 = new UserDTO(0, "", "", "", 0, userType0);
      String string0 = userDTO0.getUserName();
      assertNotNull(string0);
      assertEquals(0.0F, userDTO0.rating, 0.01F);
      assertEquals(0, userDTO0.id);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      userDTO0.setRating(1121.7086F);
      float float0 = userDTO0.getRating();
      assertEquals(1121.7086F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      userDTO0.rating = (-2101.972F);
      float float0 = userDTO0.getRating();
      assertEquals((-2101.972F), float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      userDTO0.lastName = "T9(QuC<";
      String string0 = userDTO0.getLastName();
      assertEquals("T9(QuC<", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      UserType userType0 = UserType.LANDLORD;
      UserDTO userDTO0 = new UserDTO((-1401), "(", "`", "`", (-1.0F), userType0);
      assertEquals("`", userDTO0.getLastName());
      
      userDTO0.setLastName("");
      userDTO0.getLastName();
      assertEquals("", userDTO0.getLastName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      UserType userType0 = UserType.TENANT;
      UserDTO userDTO0 = new UserDTO(2, "']K.;Z[", "']K.;Z[", "", 2, userType0);
      int int0 = userDTO0.getId();
      assertEquals(2, int0);
      assertEquals("", userDTO0.getLastName());
      assertEquals(2.0F, userDTO0.rating, 0.01F);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      userDTO0.setId((-1));
      int int0 = userDTO0.getId();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      UserType userType0 = UserType.LANDLORD;
      UserDTO userDTO0 = new UserDTO(0, "", "", "", 0, userType0);
      String string0 = userDTO0.getFirstName();
      assertEquals(0.0F, userDTO0.rating, 0.01F);
      assertNotNull(string0);
      assertEquals(0, userDTO0.id);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      userDTO0.getUserType();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      userDTO0.setFirstName("");
      assertNull(userDTO0.getUserName());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      String string0 = userDTO0.getUserName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      float float0 = userDTO0.getRating();
      assertEquals(0.0F, float0, 0.01F);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      int int0 = userDTO0.getId();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      UserDTO userDTO0 = new UserDTO();
      String string0 = userDTO0.getLastName();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      UserType userType0 = UserType.LANDLORD;
      UserDTO userDTO0 = new UserDTO(1710, "K-NbO9X0ASIg!bVi", "K-NbO9X0ASIg!bVi", "", 1.0F, userType0);
      String string0 = userDTO0.getFirstName();
      assertEquals(1710, userDTO0.id);
      assertEquals("K-NbO9X0ASIg!bVi", string0);
      assertEquals("", userDTO0.getLastName());
      assertNotNull(string0);
      assertEquals(1.0F, userDTO0.rating, 0.01F);
  }
}
