/*
 * This file was automatically generated by EvoSuite
 * Tue Nov 13 12:19:30 GMT 2018
 */

package com.landlord.api.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import com.landlord.dto.RatingVoteDTO;
import com.landlord.models.RatingVote;
import com.landlord.utils.VotingInputMapperImpl;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class VotingInputMapperImpl_ESTest extends VotingInputMapperImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      VotingInputMapperImpl votingInputMapperImpl0 = new VotingInputMapperImpl();
      RatingVoteDTO ratingVoteDTO0 = votingInputMapperImpl0.map((RatingVote) null);
      assertNull(ratingVoteDTO0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      VotingInputMapperImpl votingInputMapperImpl0 = new VotingInputMapperImpl();
      List<RatingVote> list0 = votingInputMapperImpl0.mapManyToModel((List<RatingVoteDTO>) null);
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      VotingInputMapperImpl votingInputMapperImpl0 = new VotingInputMapperImpl();
      List<RatingVoteDTO> list0 = votingInputMapperImpl0.mapMany((List<RatingVote>) null);
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      VotingInputMapperImpl votingInputMapperImpl0 = new VotingInputMapperImpl();
      RatingVote ratingVote0 = votingInputMapperImpl0.map((RatingVoteDTO) null);
      assertNull(ratingVote0);
  }
}
